// Code generated by mockery v2.53.3. DO NOT EDIT.

package mock_repository

import (
	context "context"
	domain "trust_wallet_homework/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// ParserStateRepository is an autogenerated mock type for the ParserStateRepository type
type ParserStateRepository struct {
	mock.Mock
}

// GetCurrentBlock provides a mock function with given fields: ctx
func (_m *ParserStateRepository) GetCurrentBlock(ctx context.Context) (domain.BlockNumber, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentBlock")
	}

	var r0 domain.BlockNumber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.BlockNumber, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.BlockNumber); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.BlockNumber)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetCurrentBlock provides a mock function with given fields: ctx, blockNumber
func (_m *ParserStateRepository) SetCurrentBlock(ctx context.Context, blockNumber domain.BlockNumber) error {
	ret := _m.Called(ctx, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrentBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BlockNumber) error); ok {
		r0 = rf(ctx, blockNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewParserStateRepository creates a new instance of ParserStateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParserStateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParserStateRepository {
	mock := &ParserStateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
