// Code generated by mockery v2.53.3. DO NOT EDIT.

package mock_repository

import (
	context "context"
	domain "trust_wallet_homework/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// MonitoredAddressRepository is an autogenerated mock type for the MonitoredAddressRepository type
type MonitoredAddressRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, address
func (_m *MonitoredAddressRepository) Add(ctx context.Context, address domain.Address) error {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Address) error); ok {
		r0 = rf(ctx, address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, address
func (_m *MonitoredAddressRepository) Exists(ctx context.Context, address domain.Address) (bool, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Address) (bool, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Address) bool); ok {
		r0 = rf(ctx, address)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Address) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *MonitoredAddressRepository) FindAll(ctx context.Context) ([]domain.Address, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Address, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Address); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMonitoredAddressRepository creates a new instance of MonitoredAddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoredAddressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoredAddressRepository {
	mock := &MonitoredAddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
