server:
  port: ":8080"                      # HTTP server listen address (e.g., ":8080" or "localhost:8080")
  read_timeout_seconds: 15           # Max duration for reading the entire request, including the body
  write_timeout_seconds: 15          # Max duration before timing out writes of the response
  idle_timeout_seconds: 60           # Max amount of time to wait for the next request when keep-alives are enabled
  read_header_timeout_seconds: 30    # Amount of time allowed to read request headers

logger:
  level: "info"                        # Logging level. Options: "debug", "info", "warn", "error"
  format: "text"                       # Logging format. Options: "json", "text"

eth_client:
  node_url: "http://localhost:8545"    # Your Ethereum JSON-RPC node URL
  client_timeout_seconds: 20           # HTTP client timeout in seconds for ETH RPC calls

app_service: # Configuration for the core application (parser) service
  polling_interval_seconds: 10       # Interval in seconds for polling new blocks from the Ethereum node
  initial_scan_from_block: -1        # Block number to start scanning from. 
                                     # -1: From latest known block in DB, or latest network block if DB is empty.
                                     #  0: From genesis block (block 0).
                                     # >0: From a specific block number.
