name: Go CI & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' 

    - name: Verify dependencies
      run: go mod tidy

    - name: Build
      run: make build

    - name: Test with Coverage
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2 
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: coverage.out 
        flag-name: run-${{ matrix.os }}-${{ matrix.go }} 
        parallel: false 